### PR TITLE
feat: redesign cash register UI

### PR DESCRIPTION
**Pull request by Extheoisah**
This PR adds the redesign of the Cash register.
However, some two components are yet to be redesigned for now - adding memo (note) and the print pay code which is about 70% done.
Due to the upcoming AB22 conference, this can be merged since the undesigned components are of low priority ATM.

### CODE REVIEW

**Review by daviroo — DISMISSED** [review]
I will approve for now - I did test locally and the memo is in a weird place on the screen.  It would be good if we could at least center it and give it a style which matches the rest of the design.

image

**Review by UncleSamtoshi — CHANGES_REQUESTED** [review]
Redesign_feedback
Redesign_Feedback_2
Some things that need to be addressed before merging in:
1. BBW logo is currently blurry
2. Memo is not centered
3. Multiple numbers are currently highlighted instead of just being highlighted when pushed
4. Galoy logo hidden when memo is present and too close to create invoice when it is not present
5. Galoy logo is blurry
6. Icon should be an 'x' for exiting out
7. `@` sign is not centered
8. If memo is present and then you go to another page and come back to the cash register, the memo disappears.

**Comment by Extheoisah** [comment]
> 

I didn't test the new design with the memo. Will fix, shouldn't be much of an effort

**Comment by Extheoisah** [comment]
> I didn't test the new design with the memo. Will fix, shouldn't be much of an effort
Where are the numbers in red coming from?

**Review by UncleSamtoshi — APPROVED** [review]

**Pull request merged**
