### PR TITLE
fix: amount becomes nan

### PR DESCRIPTION
**Pull request by Toheeb-Ojuolape**
Changed the logic for usdValueInSats to that of a ternary operator to reduce the need to call the satToUsd function to get the dollar equivalent in Sats

### CODE REVIEW

**Review by Extheoisah — COMMENTED** [review]
This doesn't solve the `NaN` issue. We get that issue when the price subscription hasn't returned a response on loading the app. So it's a race condition. There is a fix for it in this PR here https://github.com/GaloyMoney/galoy-pay/pull/434/files#diff-09d5ecf73286dd60efda8c21b1c157be76eb6098dc986564cb8877cc1400fa21R48

**Comment by Toheeb-Ojuolape** [comment]
Oh. But I noticed that the dollar amount which is being gotten from the satsToUsd util function is typically the same as the value being passed as amount in the url query parameters for the payment, that's why I thought getting the dollar equivalent of Sats from there would fix the NaN issue, since this approach doesn't take a while to load unlike the satsToUsd

**Comment by Extheoisah** [comment]
> Oh. But I noticed that the dollar amount which is being gotten from the satsToUsd util function is typically the same as the value being passed as amount in the url query parameters for the payment, that's why I thought getting the dollar equivalent of Sats from there would fix the NaN issue, since this approach doesn't take a while to load unlike the satsToUsd

That makes sense. 
This is a much better approach to Getting the amount paid. The NaN issue occurs when you load the app before creating an invoice. So its a different issue

**Review by Extheoisah — APPROVED** [review]
I'm approving nonetheless. 👍 since it simplifies the logic

**Comment by Toheeb-Ojuolape** [comment]
Thank you so much!

**Pull request merged**
