### PR TITLE
add open with wallet to invoice page

### PR DESCRIPTION
**Pull request by pseudozach**
I've added an additional link, so users can tap to pay open their wallets to pay the invoice which is very useful specially on Android phones where you can select `open with app`.

This is halfway between making the QR clickable and doing a whole new design with additional copy/tap to open buttons which would change the nice clean UI.

I hope you'll consider it. I'm happy to make any changes as well.

Here's a simple demo video: https://www.youtube.com/watch?v=H1t-eQjiltM
reference discussion: https://twitter.com/nicolasburtey/status/1411754381280694273?s=20

### CODE REVIEW

**Review by krtk6160 — APPROVED** [review]

**Comment by krtk6160** [comment]
@pseudozach Thanks for the contribution!

**Comment by pseudozach** [comment]
thanks for merging happy to help!

**Comment by vindard** [comment]
@bumi the same thing you were suggesting

**Comment by bumi** [comment]
whoot, nice! that's great, very useful to use it. 

(now we only need to add [WebLN](https://webln.dev/) )

**Pull request merged**
